services:
  backend:
    build: ./backend
    container_name: pollution_backend
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: pollution_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Important pour ne pas écraser les packages installés dans Docker
    environment:
      - VITE_WS_TARGET=ws://localhost:8000/ws
    command: npm run dev -- --host 0.0.0.0
